# Generated by Django 2.2.2 on 2019-08-07 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('pass_word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(verbose_name='last login time')),
                ('login_false', models.CharField(max_length=10)),
                ('userID_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password.User')),
            ],
        ),
    ]
