# Generated by Django 2.2.2 on 2019-08-07 09:06

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pass_word',
            new_name='password',
        ),
    ]
