# Generated by Django 2.2.2 on 2019-08-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('password', '0002_auto_20190807_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='challen_num',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
