# Generated by Django 2.2.2 on 2019-08-09 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('password', '0003_login_challen_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLogSection',
            fields=[
                ('ID_section', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BinaryField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LoginSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challen_num', models.CharField(max_length=10)),
                ('login_time', models.DateTimeField()),
                ('login_false', models.CharField(max_length=10)),
                ('ID_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password.LoginLogSection')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userID',
            new_name='ID_user',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='loginlogsection',
            name='ID_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password.User'),
        ),
    ]
