# Generated by Django 2.2.2 on 2019-08-09 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0005_auto_20190809_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsection',
            name='ID_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loginsection', to='password.LoginLogSection'),
        ),
    ]
