# Generated by Django 2.2.4 on 2019-08-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0007_user_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSalt',
            fields=[
                ('us_IDuser', models.AutoField(primary_key=True, serialize=False)),
                ('us_username', models.CharField(max_length=100)),
                ('us_password', models.CharField(max_length=100)),
                ('us_salt', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
