# Generated by Django 2.2.4 on 2019-08-11 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0008_auto_20190810_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSaltSection',
            fields=[
                ('uss_IDsection', models.AutoField(primary_key=True, serialize=False)),
                ('uss_fistTime', models.DateField()),
                ('uss_status', models.BooleanField(default=False)),
                ('uss_IDuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password.UserSalt')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_FalseTimes', models.CharField(max_length=10)),
                ('s_lastTime', models.DateField()),
                ('s_IDsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password.UserSaltSection')),
            ],
        ),
    ]
