# Generated by Django 2.2.4 on 2019-08-11 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0009_section_usersaltsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='s_IDsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='password.UserSaltSection'),
        ),
    ]
