# Generated by Django 2.2.4 on 2019-08-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0011_auto_20190811_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='s_FalseTimes',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='s_lastTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usersaltsection',
            name='uss_fistTime',
            field=models.DateTimeField(),
        ),
    ]
