# Generated by Django 2.2.4 on 2019-08-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0012_auto_20190811_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersalt',
            name='us_lock',
            field=models.BooleanField(default=False),
        ),
    ]
