# Generated by Django 2.2.4 on 2019-08-28 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macBellLaPadula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='name',
        ),
        migrations.AddField(
            model_name='object',
            name='filename',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='object',
            name='title',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='object',
            name='path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sc_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='macBellLaPadula.User'),
        ),
    ]
