# Generated by Django 2.2.4 on 2019-08-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macBellLaPadula', '0002_auto_20190828_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='filename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='object',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
